# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        threads:
          max: 1000
          min-spare: 30
    port: 9091
spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      druid:
        url: jdbc:sqlserver://10.41.253.2:1433;DatabaseName=MMIS
        username: sa
        password: 123456
        initial-size: 10
        max-active: 100
        min-idle: 10
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          #login-username: admin
          #login-password: admin
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: false
          wall:
            config:
              multi-statement-allow: true
    application:
      name: tfjc
    mvc:
      static-path-pattern: /static/**
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
    activiti:
#      database-schema-update: drop-create
#      database-schema-update: false
      database-schema-update: true
#      database-schema-update: create-drop
      check-process-definitions: false
#      historyLevel: none
#      historyLevel: activity
#       默认
      historyLevel: audit
#      historyLevel: full
      db-history-used: true
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

opcua:
  servers[0]:
    endpoint-url: opc.tcp://10.41.253.17:4840
    client-handle: 100
    #username: administrator
    #password: Ne2Opc2020
